Repository airmap/platform-sdk, pull requests merged in 2018-09, with the labels that each got.

#113 [circleci] Add clang and Android NDK builds
  .circleci/config.yml
  tools/android/download-ndk.sh
  tools/ubuntu/setup.dev.sh
Labels: android

#115 [codec] Handle missing fields gracefully
  src/airmap/codec/json/traffic.cpp
Labels: bug

#116 [macOS] Account for unsupported compiler flag
  vendor/boringssl/CMakeLists.txt
Labels: bug

#121 Add contributing doc
  CONTRIBUTING.md
Labels: enhancement
